# Generated by Django 4.0.2 on 2022-03-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default='Avatar.png', upload_to='profile'),
        ),
    ]
