# Generated by Django 4.0.2 on 2022-04-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0002_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_loc', models.CharField(max_length=30)),
                ('drop_loc', models.CharField(max_length=30)),
                ('p_date', models.DateField()),
                ('d_date', models.DateField()),
                ('pick_time', models.CharField(max_length=10)),
            ],
        ),
    ]
