# Generated by Django 4.0.2 on 2022-04-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0003_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='d_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='p_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
