# Generated by Django 4.0.2 on 2022-04-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0004_alter_trip_d_date_alter_trip_p_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='d_date',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='p_date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
