# Generated by Django 4.0.2 on 2022-04-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0005_alter_trip_d_date_alter_trip_p_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycar.user'),
        ),
    ]
