# Generated by Django 4.0.2 on 2022-04-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0006_trip_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=30)),
                ('car_pic', models.FileField(upload_to='cars')),
                ('p_hour', models.IntegerField(default=0)),
                ('p_day', models.IntegerField(default=0)),
                ('fuel_type', models.CharField(max_length=10)),
            ],
        ),
    ]
