# Generated by Django 4.0.2 on 2022-04-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0007_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('pay_id', models.CharField(blank=True, max_length=50, null=True)),
                ('verify', models.BooleanField(default=False)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.car')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycar.user')),
            ],
        ),
    ]
